package com.example.aiplatform.ai.llm;

import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.tool.ToolCallbackProvider;
import reactor.core.publisher.Flux;

/**
 * Thin seam over whichever LLM provider is wired up. Keeps callers (the
 * business service layer) from depending on a specific provider's SDK or
 * Spring AI's fluent API directly, per the "no LLM provider lock-in" rule.
 *
 * Takes a fully-formed {@link Prompt} rather than a raw string so that all
 * prompt-engineering concerns (system persona, templating, few-shot
 * examples) stay in the ai/prompt layer instead of leaking in here.
 */
public interface LlmClientService {

    String generate(Prompt prompt);

    /**
     * Same as {@link #generate(Prompt)}, but makes the given tool objects'
     * {@code @Tool}-annotated methods available for the model to call. The
     * full tool-calling loop (model requests a call, the method runs, the
     * result goes back to the model, the model produces a final answer) is
     * handled internally by the provider integration - this call still
     * returns only the final text answer.
     */
    String generateWithTools(Prompt prompt, Object... tools);

    /**
     * Same as {@link #generateWithTools(Prompt, Object...)}, but for tools
     * sourced from a {@link ToolCallbackProvider} rather than annotated Java
     * objects - the seam Phase 13's MCP client demonstration uses, since an
     * MCP-discovered tool is already a {@code ToolCallback}, not a POJO with
     * {@code @Tool} methods to reflect over.
     */
    String generateWithTools(Prompt prompt, ToolCallbackProvider toolCallbackProvider);

    /**
     * The same generation, delivered incrementally.
     *
     * <p>Latency and <em>perceived</em> latency are different numbers, and only
     * one of them is what a user experiences. A grounded answer legitimately
     * takes 6-15 seconds to produce in full; streaming does not make it
     * arrive any sooner, but it replaces fifteen seconds of nothing with a
     * first token in well under one. That is the single largest improvement
     * available to this application's felt responsiveness, and it costs no
     * provider capability the non-streaming path has.
     *
     * <p>Returns a {@link Flux} of content deltas - the provider's own chunks,
     * not re-segmented - which the controller adapts to server-sent events.
     * {@code Flux} rather than a callback or a blocking iterator because it is
     * what Spring AI's streaming API already produces and what Spring MVC's
     * {@code ResponseBodyEmitter} machinery already knows how to consume; an
     * intermediate abstraction here would add a layer and remove nothing.
     *
     * <p><b>What streaming gives up.</b> Output guardrails that need the whole
     * response cannot run on a token that has already been sent - see the
     * implementation for how that is handled and what it means for callers.
     */
    Flux<String> generateStream(Prompt prompt);

    /**
     * The provider model name backing a given tier.
     *
     * <p>Exists so response DTOs can report which model answered without four
     * services each injecting {@code ${spring.ai.openai.chat.options.model}}.
     * That property is provider-specific by construction, and injecting it into
     * a business service put an OpenAI-shaped configuration key in the middle
     * of the layer this seam exists to keep provider-neutral - the same leak
     * {@link com.example.aiplatform.ai.embedding.EmbeddingService#modelName()}
     * already closed on the embedding side. The concrete adapter is once again
     * the only place that knows where the name comes from.
     */
    String modelName(ModelTier tier);

    /** The model a human-read answer is generated by - the one worth reporting to a caller. */
    default String modelName() {
        return modelName(ModelTier.CAPABLE);
    }
}
